# Generated by Django 4.1.5 on 2023-01-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=250)),
                ('stock', models.IntegerField(default=0)),
                ('batch_code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='KitInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('sumary', models.CharField(max_length=150)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('public', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exp_date', models.DateTimeField()),
                ('size', models.CharField(max_length=80)),
                ('weight', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=250)),
                ('type_ac', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('batch_code', models.CharField(max_length=150)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.provider')),
            ],
        ),
        migrations.CreateModel(
            name='LoteKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default=0)),
                ('exp_date', models.DateTimeField()),
                ('consumables', models.ManyToManyField(to='laboratory.consumables')),
                ('kit_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.kitinformation')),
                ('reactives', models.ManyToManyField(to='laboratory.reagent')),
            ],
        ),
        migrations.AddField(
            model_name='consumables',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.provider'),
        ),
    ]
