# Generated by Django 4.1.5 on 2023-01-18 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumables',
            options={'verbose_name': 'Consumible', 'verbose_name_plural': 'Consumibles'},
        ),
        migrations.AlterModelOptions(
            name='kitinformation',
            options={'verbose_name': 'Información de kit', 'verbose_name_plural': 'Información de kits'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localización', 'verbose_name_plural': 'Localizaciones'},
        ),
        migrations.AlterModelOptions(
            name='lotekit',
            options={'verbose_name': 'Stock de lote', 'verbose_name_plural': 'Stock de lotes'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reagent',
            options={'verbose_name': 'Reactivo', 'verbose_name_plural': 'Reactivos'},
        ),
    ]
